In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.linspace(0,49,6)

array([ 0. ,  9.8, 19.6, 29.4, 39.2, 49. ])

In [9]:
np.random.rand(6)

array([0.19109107, 0.70046731, 0.75155593, 0.25782946, 0.10888295,
       0.0642147 ])

In [10]:
np.random.rand((2,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [11]:
np.random.rand(2,3)

array([[0.16830431, 0.45567067, 0.7536929 ],
       [0.38733183, 0.11499771, 0.38912305]])

In [12]:
#np.random.randint will give any random integer between low and high ranges
np.random.randint(5)

0

In [13]:
np.random.randint(2,5)

4

In [15]:
my_array = np.random.randint(2,7,5)

In [16]:
my_array

array([6, 6, 3, 4, 4])

In [17]:
my_array.max()

6

In [18]:
my_array.min()

3

In [19]:
my_array.argmax

<function ndarray.argmax>

In [20]:
my_array.argmax()

0

In [21]:
my_array.argmin()

2

In [22]:
my_array.reshape(1,5)

array([[6, 6, 3, 4, 4]])

In [24]:
new_array = my_array.reshape(5,1)

In [26]:
new_array.shape

(5, 1)

In [27]:
new_array[3] = 7

In [28]:
new_array

array([[6],
       [6],
       [3],
       [7],
       [4]])

In [29]:
arr1 = my_array.copy()

In [30]:
arr1

array([6, 6, 3, 7, 4])

In [31]:
arr1[3] = 15
arr1

array([ 6,  6,  3, 15,  4])

In [32]:
my_array

array([6, 6, 3, 7, 4])

In [33]:
arr2d = np.array([[2,3,4],[5,6,7],[11,23,45]])

In [34]:
arr2d[1][1]

6

In [35]:
arr2d[2,1]

23

In [36]:
arr2d[1:,1:]

array([[ 6,  7],
       [23, 45]])

In [37]:
my_array > 5

array([ True,  True, False,  True, False])

In [38]:
my_array[my_array > 5]

array([6, 6, 7])

In [39]:
my_array + 10

array([16, 16, 13, 17, 14])